---

# task file for dgnest.deployment

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install deployment package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_deployment_package_dependencies
  when: _deployment_package_dependencies is defined
  with_items: _deployment_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_deployment_package_dependencies.stdout_lines

- name: Install deployment dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_deployment_dependencies
  when: _deployment_dependencies is defined
  with_items: _deployment_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_deployment_dependencies.stdout_lines
