---
# task for dgnest.deployment

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - deployment

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - deployment
