---
# task for dgnest.deployment

- name: Install packages via pip deployment
  become: yes
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: deployment_pip_dependencies is defined
  with_items: deployment_pip_dependencies
