---
# tasks file for dgnest.deployment (CentOS specific)

- name: Ensure apt cache is up to date
  yum:
    update_cache: yes


- name: Install deployment dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items: _deployment_packages
  tags:
    - deployment
