# ~/.tmuxinator/ansible-role-deployment.yml
name: ansible-role-deployment
root: <%= ENV["PROJECTS"] %>/ansible/roles/ansible-role-deployment
tmux_options: -2
# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start
pre:
    - make environment

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t ansible-role-deployment

windows:
  - editor:
      layout: even-horizontal
      panes:
        - editor:
            - pyenv activate ansible-role-deployment
            - <%= ENV["EDITOR"] %>
        - vagrant:
            - pyenv activate ansible-role-deployment
        - docker:
            - pyenv activate ansible-role-deployment
  - python:
      layout: main-vertical
      panes:
        - python:
            - pyenv activate ansible-role-deployment
            - ipython
  - databases:
      layout: main-vertical
      panes:
        - postgresql:
            - pyenv activate ansible-role-deployment
        - mysql:
            - pyenv activate ansible-role-deployment
  - docker:
      layout: main-vertical
      panes:
        - code:
            - pyenv activate ansible-role-deployment
        - vagrant:
            - pyenv activate ansible-role-deployment
